users:
  - email: manager@example.com
    password: SecurePassword123!
    firstName: Manager
    lastName: User
    role: Manager

  - email: customer@example.com
    password: UserPassword123!
    firstName: Regular
    lastName: User
    role: Customer

  - email: barista@example.com
    password: BaristaPassword123!
    firstName: Barista
    lastName: User
    role: Barista
